name: DBB-TEST
favicon: null
layout_spectrum: 0.6476353676989675
typography_spectrum: 0.5050857048481703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.05308051290921867
  lightness: 0.053714397829025984
  saturation: 0.3353392113931477
  rhythmicContrast: 0.33739919355139136
purpose: []
